# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#         _           _         _                                 #
#        | |         (_)       | |                                #
#    ___ | | __ _ __  _  _ __  | |_  ______  _ __   _ __    ___   #
#   / __|| |/ /| '__|| || '_ \ | __||______|| '_ \ | '_ \  / __|  #
#   \__ \|   < | |   | || |_) || |_         | | | || |_) || (__   #
#   |___/|_|\_\|_|   |_|| .__/  \__|        |_| |_|| .__/  \___|  #
#                       | |                        | |            #
#                       |_|                        |_|            #
#                                                                 #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                 #
#                                            by NanoDankster      #
#                            https://github.com/NanoDankster      #
#                                                                 #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Just a reminder, I'm against version checks ;)
version: 0.1

# Metrics are good ;)
enable-metrics: true